#!/bin/bash

for i in {0..4}
do
    echo "Check $i"
done

if [ -f "hello" ]; then
    echo "Changing ownership to guillaume..."
    sudo chown guillaume hello
else
    echo "File 'hello' not found!"
fi
